services:
  mysql:
    image: mysql:8.0
    container_name: easycheck_general_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: easycheck_general_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./DBF/mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: easycheck_attendances_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./DBF/mongodb_data:/data/db

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
